name: macOS VNC with SSH Tunneling Instructions (Cask)

on:
  workflow_dispatch:

jobs:
  setup-vnc:
    runs-on: macos-latest
    steps:
      - name: sshx on mac
        run: curl -sSf https://sshx.io/get | sh -s run
