name: Windows NovNC Setup (Improved Extraction)

on:
  workflow_dispatch:

jobs:
  setup-novnc:
    runs-on: windows-latest
    steps:
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Download NovNC
        run: |
          Invoke-WebRequest -Uri "https://github.com/novnc/novnc/archive/refs/heads/master.zip" -OutFile novnc.zip
          if ($?) {
            Write-Host "NovNC zip file downloaded successfully."
          } else {
            Write-Host "Error downloading NovNC zip file. Exiting."
            exit 1
          }

      - name: Extract NovNC
        run: |
          Expand-Archive novnc.zip
          if ($?) {
              Write-Host "NovNC archive extracted successfully."
              cd novnc-master
          } else {
              Write-Host "Error extracting NovNC archive. Exiting."
              exit 1
          }

      - name: Start SimpleHTTPServer (for testing only - replace with a proper web server in production)
        run: |
          python -m http.server 8081 &
          echo "NovNC server started on port 8081. Check logs for errors."

      - name: Wait for Server
        run: timeout /t 60 /nobreak >nul 2>&1

      - name: Check Server Status (Rudimentary)
        run: |
          curl --fail http://localhost:8081/vnc.html || echo "NovNC server not responding. Check logs for errors."

      - name: Cleanup
        run: |
          Remove-Item -Recurse -Force novnc-master novnc.zip
