name: Windows Apache with VNC Proxy

on:
  workflow_dispatch:

jobs:
  setup-apache:
    runs-on: windows-latest
    steps:
      - name: Install Apache
        uses: mikesdotnetautomator/install-apache-on-windows@v1 #This action might need adjustments based on its updates

      - name: Enable Proxy Modules
        run: |
          #This assumes the Apache installation is standard.  Adjust paths as needed.
          httpd.exe -k install
          httpd.exe -M #Check if modules are already loaded.
          #If not loaded, uncomment and run the commands below
          #apachectl.exe -M | findstr "proxy"
          #apachectl.exe -M | findstr "proxy_http"
          #If the modules are not loaded, you'll need to uncomment the lines below and adjust paths as necessary.  Consult Apache documentation for your specific version
          #echo "Enabling proxy modules..."
          #REM Uncomment the below lines if modules are not already enabled
          #httpd.exe -M | findstr "proxy" >nul || (echo "LoadModule proxy_module modules/mod_proxy.so" >> httpd.conf)
          #httpd.exe -M | findstr "proxy_http" >nul || (echo "LoadModule proxy_http_module modules/mod_proxy_http.so" >> httpd.conf)
          #httpd.exe -k restart

      - name: Configure Apache Proxy (replace placeholders!)
        run: |
          echo "<VirtualHost *:80>" >> httpd-vhosts.conf
          echo "  ProxyPass /vnc http://<vnc_server_address>:<vnc_server_port>/" >> httpd-vhosts.conf
          echo "  ProxyPassReverse /vnc http://<vnc_server_address>:<vnc_server_port>/" >> httpd-vhosts.conf
          echo "</VirtualHost>" >> httpd-vhosts.conf
          #This assumes httpd-vhosts.conf is in the correct Apache configuration directory. Adjust as needed.
          Move-Item -Force httpd-vhosts.conf "C:\Program Files\Apache Software Foundation\Apache2.4\conf\extra\"
          httpd.exe -k restart

      - name: Display Access Instructions
        run: |
          echo "To access VNC via Apache:"
          echo "1. Connect to the runner via SSH (find the connection string in the workflow logs)."
          echo "2. Forward port 80 locally using a command like this:"
          echo "   ssh -L 80:localhost:80 <your_username>@<runner_ip_or_hostname>"
          echo "3. Open your browser and go to http://localhost/vnc"


      - name: Cleanup
        run: |
          Remove-Item -Force httpd-vhosts.conf
