name: Windows collaboration

on:
  workflow_dispatch:

jobs:
  sshx-job:
    runs-on: windows-latest
    steps:
      - name: Download SSHX ZIP
        run: Invoke-WebRequest -Uri "https://sshx.s3.amazonaws.com/sshx-x86_64-pc-windows-msvc.zip" -OutFile "sshx-installer.zip"

      - name: Extract SSHX
        run: Expand-Archive -Path "sshx-installer.zip" -DestinationPath "sshx"

      - name: Run SSHX command
        run: .\sshx\sshx.exe 
